const pcConfig = {
  columns: {
    si_no: 'S No.',
    type: 'Type',
    product_master_name: 'Product Master',
    medseven_product_name: 'Medseven',
    tamimi_product_name: 'Tamimi',
    sharjah_product_name: 'Sharjah',
    sultan_product_name: 'Sultan',
    product_supplier: 'Supplier',
    remarks: 'Remarks',
    moh: 'MOH',
    medseven_price: 'Medeseven Price',
    sharjah_price: 'Sharjah Price',
    sultan_base_price: 'Sultan Base',
    sultan_scheme: 'Sultan Scheme',
    sultan_price_1: 'Sultan Price 1',
    sultan_price_2: 'Sultan Price 2',
    sultan_price_3: 'Sultan Price 3',
    sultan_bonus_1: 'Sultan Bonus 1',
    sultan_bonus_2: 'Sultan Bonus 2',
    sultan_bonus_3: 'Sultan Bonus 3',
    tamimi_base_price: 'Tamimi Base',
    tamimi_price_1: 'Tamimi Price 1',
    tamimi_price_2: 'Tamimi Price 2',
    tamimi_price_3: 'Tamimi Price 3',
    tamimi_bonus_1: 'Tamimi Bonus 1',
    tamimi_bonus_2: 'Tamimi Bonus 2',
    tamimi_bonus_3: 'Tamimi Bonus 3'
  },
  defaultValues: {
    si_no: '#',
    type: '',
    product_master_name: '',
    medseven_product_name: '',
    tamimi_product_name: '',
    sharjah_product_name: '',
    sultan_product_name: '',
    product_supplier: '',
    remarks: '',
    moh: '',
    medseven_price: '',
    sharjah_price: '',
    sultan_base_price: '',
    sultan_scheme: '',
    sultan_price_1: '',
    sultan_price_2: '',
    sultan_price_3: '',
    sultan_bonus_1: '',
    sultan_bonus_2: '',
    sultan_bonus_3: '',
    tamimi_base_price: '',
    tamimi_price_1: '',
    tamimi_price_2: '',
    tamimi_price_3: '',
    tamimi_bonus_1: '',
    tamimi_bonus_2: '',
    tamimi_bonus_3: ''
  }
}

module.exports = pcConfig
