export Home from './Home/Home'
export Admin from './Admin/Admin'
export Layout from './Layout'
export Upload from './Upload/Upload'
export App from './App/App'
export NotFound from './NotFound'
export Test from './Test/Test'
export Login from './Login/Login'
