export Home from './Home/Home.jsx'
export Admin from './Admin/Admin.jsx'
export Layout from './Layout.jsx'
export Upload from './Upload.jsx'
export App from './App/App.jsx'
export NotFound from './NotFound.jsx'
export Test from './Test/Test.jsx'
